### ISSUE TITLE
METS模型

### ISSUE THREAD

**Issue by LewisJeny** [JerryKingQAQ/METS#1]
你好，我最近也在尝试复现这篇论文的代码，但是我发现做出来的结果很不理想，我在ptb-xl数据库上面预训练并zero-shot，精确率只有20%左右，请问能够交流一下吗？

**Comment by JerryKingQAQ** [comment]
Hi! 我目前只是单纯将整个思路写了一下，并没有在数据集上进行训练和测试，所以我也不太清楚具体的结果。不过我感觉这篇论文的整体思路是没有问题的。
